production: &defaults
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: app_dev
  pool: 5
  username: root
  password: enbake

development:
  <<: *defaults
  database: app_dev

test:
  <<: *defaults
  database: app_test
