# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9224d5932efbd687ad6a77d5e74a7ff0b82badb2ca09dfae5a9c181408044e47b835aac0e59ba9a9c8b11e13ec66d64e9794f79731905fe4ff27e4b55524ebef

test:
  secret_key_base: bb677446eccddf6c898bb1f8f2166851d20b2623d2834b3a57d818e2b12a512fc62d3deccfd011a6ed61defbc2371cfe195085f038b5be89d03af57cfe99a979

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
